services:
  database:
    image: postgres:latest
    container_name: postgres-rutok
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rutok
    ports:
      - 8888:5432