services:
  database:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=rutok
      - POSTGRES_PASSWORD=rutok
      - POSTGRES_DB=rutok
    ports:
      - 5432:5432