#
# Spring
#
spring.application.name=${APP_NAME:@project.artifactId@}
spring.application.description=${APP_DESCR:Rutok auth service}
spring.application.version=${APP_VERSION:@project.version@}
server.port=${SERVER_PORT:8080}
#
# Database
#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:8888/${DB_NAME:rutok}?currentSchema=rutok_auth}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASS:admin}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.check_nullability=true
spring.jpa.properties.hibernate.hbm2ddl.auto=validate
#
# Liquibase
#
spring.liquibase.enabled=true
spring.liquibase.liquibase-schema=public
spring.liquibase.database-change-log-table=rutok_auth_log
spring.liquibase.database-change-log-lock-table=rutok_auth_lock
spring.liquibase.change-log=classpath:db/changelog.yaml
#
# Logging
#
logging.level.root=${LOGGING_LEVEL_DEFAULT:INFO}
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.org.postgresql=WARN
logging.level.org.apache.tomcat.util=WARN
#
# JWT
#
jwt.privateKey=${JWT_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCql14eOnJur4SGu5UYlLPfWxj6teyC/1sqRaGrVonWuFE4gKa392PUQsOwwseawagvPnqcu9aILOYfBZRX2EzbgaKJ0fLLH5DAGdqInIPAT4T2slQCLkoa0HnVhOkMZltTDz5LxhQlqYmlvtzokP3ZvNk5oGR98xTW9wwULikgs1LSOlUXksd4RBjN30jn+2XgX7FIhR2rkx1o1q0MDNtQZAG7LenKMpLVZJmtmFIW2Jjr8J8vFZ7ssGhnNwLSybqDE9sC2ugmcFQxIhy+hFYJsuey5/p4wjt3HmrxaMDgb0rCyJcHwRHtg80Rt9tp6zNAePib96txT+m7T025O/hJAgMBAAECggEACBQN9XGAHMS8CmNUrqrQD8oxFyJJVnTAPPK6MrJw6ZWl5v6Upo6VECavPK4kpKv6Cm6zgLuWb7Fsnlh1y2knTpfHei5SiJLwmGBBDIoY5SD+423Tc5z8jmOD+XwHSzqHpZnJse3p41Sxe4Nb07mWA9shEE0LpTk/KeTeEhCTiwRO/LtQlKFCsLeMDCloFdmFldRiMqf0rJ09KNIEvLDGSF0YxRJc3ebwnEcEOq6vCdMixEVfaA1GelkXl/6duW7Ut7C321AwTXz//jJUBX9wl0RVYJmxJ/fjsLoQNOHTw7AevxZscxmMYZeu5ELXCJl6tio3r2MghB9WqwcZgDXhNwKBgQDsbK5uVP1m/0+w7N4TFUWiGSS7WFjd2MA7tI22XH9wei7dg1uBkD6k93x6AoqzZmaRaOxF86MFqYMRts0TglJ9IRZsJHM/1kXMAp32thiEFS8mBX8FW685srQ57t++rtF1Eqk0Nq8ViYfti9docQHGUx/KC3HClbqdEatOOS7/dwKBgQC4t0RGx7X5Z/vj7ESfl5lP2rMvGUe7TTN+Qrns71sFCSdQVcEB4Pb67FTiCJnptf+8P+biyU+pqtEfVTTglhSnn/wRcvYQBs9NZKSMVO55GVoBhzZpp7tkXxlmge8y0abfXPYOgzPEH1lVMiyPjylo/0EGghpvtEo2PLGbK3g2PwKBgQDA9h8Tu9gqZTy0iU7jQlxX5a+eHIhDYLHcyQtUiIAW3BI+BwT7ZTBL0hZNOp/btjsGeR1GJoiqiWSJY6pTPu12ZTf4wXMy6f6DeKtWfd7ahrO5k4jNZbxJGjqQgg8pgWNA6x8gl3Uk3eAMGDOScZFiPdvXOqn5h90MbyxiprdeFwKBgHjxzmvF0fnmwwBesCQK4CBwI0jgdZ5HE0NFr3Va1675altoesKfKTfszDtfxF9JgpQhBy1RAK8oIFsysDepLQcAcsx+CG0/+DZFgpQ7/BUgq1U60j7ly4YR2pDK3PLaYTf5J0cjUx7EI/rrqk+pPkT4dPws7eBcHQdcQDJIiSKDAoGAJtvGmTHkjfDITFj/bVUIlQ439QY/kyJJRfl7mBbmsA2chPBR97d6WZi3zKiVETJGBJh8SRu/4pj3C/xAsJPCXvPatG/ZIsHVqzI0voACi27LcglX3ympLqMfMo6dG8i8uXuZUMhiHBNeCioqya9DzqzK4ftZHvWfpa79rvlk/7I=}
jwt.publicKey=${JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqpdeHjpybq+EhruVGJSz31sY+rXsgv9bKkWhq1aJ1rhROICmt/dj1ELDsMLHmsGoLz56nLvWiCzmHwWUV9hM24GiidHyyx+QwBnaiJyDwE+E9rJUAi5KGtB51YTpDGZbUw8+S8YUJamJpb7c6JD92bzZOaBkffMU1vcMFC4pILNS0jpVF5LHeEQYzd9I5/tl4F+xSIUdq5MdaNatDAzbUGQBuy3pyjKS1WSZrZhSFtiY6/CfLxWe7LBoZzcC0sm6gxPbAtroJnBUMSIcvoRWCbLnsuf6eMI7dx5q8WjA4G9KwsiXB8ER7YPNEbfbaeszQHj4m/ercU/pu09NuTv4SQIDAQAB}
